### ISSUE TITLE
Mirror and proxy support?

### ISSUE THREAD

**Issue by clarkttfu** [VMwareFusion/nautilus#16]
Hi there,

Is there anyway to support a docker hub mirror?
Is there an option to config proxy server for the engine?

Thanks,
Clark

**Comment by jeffwubj** [comment]
Hey Clark,
That's not available at the moment, planed it in the backlog

**Comment by xisheng** [comment]
Hi, Clark
Instead of configuring the docker hub mirror in configuration files, you can use the FULL URL directly to pull images from the specified docker hub mirror. eg: docker.io.mirror/library/xxxx
When pulling images, also you could set the proxy in the session where "vctl pull" commands will be executed. eg: export https_proxy=http://x.y.z:3128, then execute the vctl pull xxxx.

**Comment by clarkttfu** [comment]
@xisheng works very well, thanks!
